name: menuly_pdv
description: "Menuly PDV - Sistema de Frente de Caixa"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  file_picker: ^8.0.0
  image: ^4.1.0
  pdf: ^3.11.0
  printing: ^5.13.0
  csv: ^6.0.0
  window_manager: ^0.5.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
